### ISSUE TITLE
Sube app INEGI 

### ISSUE THREAD

**Issue by fer-gandara** [mxabierto/dgm#315]
```
---
published: true
layout: app

title: Mapa Digital de México
date: 2015-07-22
cover: apps/obrapublica/obrapublica-cover.png
screenshots: @carlosmaya @chuckcfs aquí van las imagenes que les mande por mail.
   - apps/obrapublica/screens/obrapublica1.png
  - apps/obrapublica/screens/obrapublica1a.png
  - apps/obrapublica/screens/obrapublica2a.png
  - apps/obrapublica/screens/obrapublica3.png
  - apps/obrapublica/screens/obrapublica3a.png
  - apps/obrapublica/screens/obrapublica5a.png
  - apps/obrapublica/screens/obrapublicaWebApp.png

links:
  web: http://www.inegi.org.mx/geo/contenidos/MapaDigital/exe/Instalar_MapaDigital_6.1.0.exe

datasets:
  -
    title:  
    url:   

app_author: Instituto Nacional de Estadística y Geografía
permalink: "/apps/mapadigital.html"
section: apps
category: web
category_title: Web
tags:
  - DENUE
  - INEGI 
---
```
El Mapa Digital de México es un Sistema de Información Geográfica (SIG), desarrollado por el INEGI, que integra información de los elementos naturales y culturales que conforman el entorno geográfico del país y permite relacionarlos con información estadística.
